name: stringcare_example
description: Demonstrates how to use the stringcare plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  stringcare:
    path: ../

  cupertino_icons: ^1.0.0

stringcare:
  assets_path: "assets"
  assets_base_path: "assets_base"
  # lang_path: "lang"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/voyager.jpeg
