name: stringcare
description: A new flutter plugin project.
version: 0.0.1
author: Efraín Espada Fraile
homepage: https://github.com/StringCare/stringcare
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^1.0.0
  crypto: ^3.0.1
  characters: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: ^1.16.7
  mockito: ^5.0.4
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.stringcare
        pluginClass: StringcarePlugin
      ios:
        pluginClass: StringcarePlugin
      macos:
        pluginClass: StringcarePlugin
      windows:
        pluginClass: StringcarePlugin
      web:
        pluginClass: StringcareWeb
        fileName: stringcare_web.dart
